### <center> R Matrices </center>

#### <center> Creating Matrices </center> 
* Vectors allow us to stored 1-dimensional index elements of the same type.
* Matrices allow us to store 2-dimensional index elements of the same type.
* First let's seehow to quickly create sequential numeric vectors using the colon **`:`** notation.

In [1]:
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

* The **`matrix()`** function creates a matrix. 
* We can pass a vector into a matrix and number of rows using **`nrow`** (default=1)
* The **`byrow`** (default=FALSE) argument is TRUE or FALSE to determine if you will fille the matrix by rows first or not.

In [7]:
# Returns a 10 row x 1 col matrix
matrix(data=v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [8]:
# Returns a 2 row x 5 col matrix
matrix(data=v, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [10]:
# Returns a 2 row x 5 col matrix, filled by column
matrix(data=v, nrow=2, byrow=TRUE)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

#### Creating Matrices from Vectors 
* We can combine vector and later put them in a matrix.
* Stock prices example:

In [11]:
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

In [12]:
stocks <- c(goog, msft)

In [13]:
stocks

[1] 450 451 452 445 468 230 231 232 236 228

In [14]:
stocks.matrix <- matrix(stocks, byrow=TRUE, nrow=2)

In [15]:
stocks.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

#### Naming Matrices
* The **`colnames()`** function names the matrix columns.
* The **`rownames()`** function names the matric rows.
* They work similarly to the **`names()`** function for vectors.
* A matrix with named rows and columns should started reminding us of a spreadsheet!

In [16]:
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')

In [18]:
colnames(stocks.matrix) <- days
rownames(stocks.matrix) <- st.names

In [19]:
stocks.matrix

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

#### <center> Matix Arithmetic </center>
* Matrix arithmetic with scalars or other matrices works element by element like with vectors.

**With scalars**

In [21]:
mat <- matrix(1:50, byrow=TRUE, nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [22]:
mat*2 # multiplication

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [24]:
mat/2 # division

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20   
[5,] 20.5 21   21.5 22   22.5 23   23.5 24   24.5 25

In [25]:
mat^2 # power

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

* We can performa comparissons across all elements of a matrix and return a matrix of logicals.

In [26]:
mat > 25

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

**Matrix by Matrix Arithmetic**

In [27]:
mat + mat # addition

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [28]:
mat / mat # division

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

**True matrix multiplication**

In [30]:
mat2 <- matrix(1:9, nrow=3)

In [31]:
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

#### <center> Matrix Operations </center>

* There are functions for many operations. Here are some examples: 

In [32]:
colSums(stocks.matrix)

Mon Tue Wed Thu Fri 
680 682 684 681 696

In [33]:
rowSums(stocks.matrix)

GOOG MSFT 
2266 1157

In [34]:
rowMeans(stocks.matrix)

GOOG  MSFT 
453.2 231.4

In [35]:
colMeans(stocks.matrix)

Mon   Tue   Wed   Thu   Fri 
340.0 341.0 342.0 340.5 348.0

#### Binding Columns and Rows 
* **`cbind()`** binds a new column to a matrix.
* **`rbind()`** binds a new row to a matrix.

In [36]:
FB <- FB <- c(111,112,113,120,145)

In [38]:
tech.stocks <- rbind(stocks.matrix, FB)

In [39]:
tech.stocks

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228
FB   111 112 113 120 145

#### <center> Matrix Selection and Indexing </center> 

* We also use the square bracket notation to select elements of a matrix.
* General format: **`matrix.name[rows, cols]`**

In [42]:
mat <- matrix(data=1:25, byrow=TRUE, nrow=5)

In [43]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [44]:
mat[1,] # select first row

[1] 1 2 3 4 5

In [45]:
mat[,1] # select first column

[1]  1  6 11 16 21

In [46]:
mat[1:3,] # grab first three rows

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15

In [47]:
mat[1:3, 1:3] # Grab top left 3x3 matrix

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  6    7    8  
[3,] 11   12   13

#### <center> Factor and Categorical Matrices </center>

* The **`factor()`** function is used for making categorical matrices. 
* This function will be exremely useful when we begin to apply data analysis and ML to our data, often to create **dummy variables**.
* Example: Animal sanctuary for dogs and cats. 

In [48]:
animal <- c("dog", "cat", "dog", "cat", "cat") 
id <- c(1, 2, 3, 4, 5)

* We want to convert the animal vector into information an algorithm or equation can understand more easily. 
* Meaning, we want to begin to check how many categories (i.e. factor levels) are in our character vector.

In [49]:
factor.ani <- factor(animal)

In [51]:
factor.ani # There are two levels/factors "cat" and "dog"

[1] dog cat dog cat cat
Levels: cat dog

* There are two kinds of categorical variables: 
    * **Nominal categorical variable**: Has no order 
    * **Orginal categorical variable**: Has order

* For ordinal categorical variables, you pass in the **`factor()`** function, arguments **`ordered=TRUE`** and **`levels = c(...)`** in the order we want them. 
* Example:

In [55]:
temps <- c("cold", "med", "cold", "med", "hot", "hot", "cold")
fact.temp <- factor(temps, ordered=TRUE, levels=c('cold','med','hot') )
fact.temp

[1] cold med  cold med  hot  hot  cold
Levels: cold < med < hot

* This information is useful when used along with the **`summary()`** function, which is very convenient in getting information from a matrix or vector. 

In [53]:
summary(temps)

   Length     Class      Mode 
        7 character character 

In [54]:
summary(fact.temp)

cold  med  hot 
   3    2    2