#### <center> R Matrices Exercises </center> 

**Ex 1**: Create 2 vectors A and B, where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 by 3 matrix from the vectors. You'll need to figure out which of these binding functions is the correct choice.

In [1]:
A <- c(1,2,3) 
B <- c(4,5,6)

In [4]:
M1 <- rbind(A, B)

In [5]:
M1

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

**Ex 2**: Create a 3 by 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable mat

In [20]:
M1 <- matrix(data=1:9, nrow=3, byrow=TRUE)

In [21]:
M1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

**Ex 3**: Confirm that mat is a matrix using is.matrix()

In [10]:
is.matrix(M1)

[1] TRUE

**Ex 4**: Create a 5 by 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5.

In [13]:
M2 <- matrix(data=1:25, nrow=5, byrow=TRUE)

In [14]:
M2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

**Ex 5**: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:

[7,8]

[12,13]

In [15]:
M2[2:3, 2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

**Ex 6**: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:

[19,20]

[24,25]

In [16]:
M2[4:5, 4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

In [17]:
sum(M2)

[1] 325

In [19]:
matrix(data=runif(n=20, min=0, max=100), nrow=4)

[,1]     [,2]       [,3]     [,4]      [,5]    
[1,] 67.84433  0.8338548 21.20449 65.205461 70.24063
[2,] 25.86894 33.4526975 69.45021  5.941737 92.64821
[3,] 30.98798 34.3439012 54.53055 62.581596 22.63815
[4,] 38.33572  7.6453055 17.13887 23.147826 52.84528