### <center> R Lists Basics </ceter> 

* Lists allows to store a variety of data structures under a single variable. 
* This means we could store a vector, matrix, data frame, etc. under a single list. 
* Example: 

In [3]:
v  <- c(1,2,3,4,5)         # Create a vector 
m  <- matrix(1:10, nrow=2) # Create a matrix 
df <- women               # Crate a data frame 

**Creating a List** 
* We can use the **`list()`** function to combine the data structures. 

In [4]:
my.list <- list(v, m, df)

In [5]:
my.list

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

* Note that `my.list` got assigned number for each object, but we can also assign names to them: 

In [7]:
my.list <- list(sample_vec = v, sample_mat = m, sample_df = df) 
my.list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

**Selecting Objects from a List**

* We can use the bracket notation to show objects in a list, and double brackets to actually grab the objects from the list.

In [8]:
my.list["sample_vec"] # Single bracket --> show object

$sample_vec
[1] 1 2 3 4 5

In [9]:
my.list[["sample_vec"]] # Double bracket --> return actual object

[1] 1 2 3 4 5

In [10]:
my.list$sample_vec # Can also use the $ notation

[1] 1 2 3 4 5

* You can also index on top of this, to grab specific element from selected object.

In [11]:
my.list[["sample_vec"]][1] # Grab first element from vector

[1] 1

In [13]:
my.list[["sample_mat"]][1,] # Grab first row of matrix

[1] 1 3 5 7 9

In [15]:
my.list[["sample_mat"]][1:2,1:2] # Grab top-left 2x2 square from matrix

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [17]:
my.list[["sample_df"]]["height"] # Grab "height" column from data frame

height
1  58    
2  59    
3  60    
4  61    
5  62    
6  63    
7  64    
8  65    
9  66    
10 67    
11 68    
12 69    
13 70    
14 71    
15 72

**Combining Lists**

* Lists can hold other lists! 
* Also, you can combine lists using the combine function **`c()`**

In [18]:
double.list <- c(my.list, my.list)

In [19]:
double.list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [20]:
str(double.list)

List of 6
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
